### ISSUE TITLE
Compilation error because of class name not match file name

### ISSUE THREAD

**Issue by mtbadi39** [kirill-grouchnikov/substance-swingx#1]
In classes : 
[org/pushingpixels/substance/swingx/svg/Dialog_information.java](https://github.com/kirill-grouchnikov/substance-swingx/blob/master/src/org/pushingpixels/substance/swingx/svg/Dialog_information.java)
[org/pushingpixels/substance/swingx/svg/Window_new.java](https://github.com/kirill-grouchnikov/substance-swingx/blob/master/src/org/pushingpixels/substance/swingx/svg/Window_new.java)

May be its [Ibis SVG transcoder](https://github.com/kirill-grouchnikov/ibis) issue because this classes has been automatically generated using it.

**Comment by kirill-grouchnikov** [comment]
Thought I updated them a couple of weeks ago. Should be good now, thanks for letting me know.
